In [1]:
#BL.EN.U4CSE21146
#Padigela Srinithya Reddy

In [2]:
import math
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [3]:
d1 = pd.read_csv("Skin_Cancer_Metadata.csv")
d1

lesion_id      image_id     dx dx_type   age     sex localization
0      HAM_0000118  ISIC_0027419    bkl   histo  80.0    male        scalp
1      HAM_0000118  ISIC_0025030    bkl   histo  80.0    male        scalp
2      HAM_0002730  ISIC_0026769    bkl   histo  80.0    male        scalp
3      HAM_0002730  ISIC_0025661    bkl   histo  80.0    male        scalp
4      HAM_0001466  ISIC_0031633    bkl   histo  75.0    male          ear
...            ...           ...    ...     ...   ...     ...          ...
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

[10015 rows x 7 columns]

In [5]:
var = d1['age'].mean()
d1['age'].fillna(var, inplace = True)

In [7]:
label_encoding = LabelEncoder()
d1['sex'] = label_encoding.fit_transform(d1['sex'])
d1.to_csv('encoded_skin_cancer.csv', index=False)

In [9]:
d1['dx_type'] = label_encoding.fit_transform(d1['dx_type'])
d1.to_csv('encoded_skin_cancer.csv', index=False)

In [8]:
d1['localization'] = label_encoding.fit_transform(d1['localization'])
d1.to_csv('encoded_skin_cancer.csv', index=False)

In [12]:
d1['dx'] = label_encoding.fit_transform(d1['dx'])
d1.to_csv('encoded_skin_cancer.csv', index=False)

In [11]:
d1 = pd.read_csv("encoded_skin_cancer.csv")
d1

lesion_id      image_id  dx  dx_type   age  sex  localization
0      HAM_0000118  ISIC_0027419   2        3  80.0    1            11
1      HAM_0000118  ISIC_0025030   2        3  80.0    1            11
2      HAM_0002730  ISIC_0026769   2        3  80.0    1            11
3      HAM_0002730  ISIC_0025661   2        3  80.0    1            11
4      HAM_0001466  ISIC_0031633   2        3  75.0    1             4
...            ...           ...  ..      ...   ...  ...           ...
10010  HAM_0002867  ISIC_0033084   0        3  40.0    1             0
10011  HAM_0002867  ISIC_0033550   0        3  40.0    1             0
10012  HAM_0002867  ISIC_0033536   0        3  40.0    1             0
10013  HAM_0000239  ISIC_0032854   0        3  80.0    1             5
10014  HAM_0003521  ISIC_0032258   4        3  70.0    0             2

[10015 rows x 7 columns]

In [13]:
# Choose two classes for binary classification ( mel and nv)
class1 = 4
class2 = 5

binary_dataset = d1[d1['dx'].isin([class1, class2])]

X = binary_dataset[['sex','localization','age']]
y = binary_dataset['dx']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

svc_lin = SVC(kernel='linear')
svc_lin.fit(X_train, y_train)

support_vectors = svc_lin.support_vectors_

# Explore the support vectors
print("Number of support vectors:", len(support_vectors))
print("Support Vectors:\n", support_vectors)

Number of support vectors: 1827
Support Vectors:
 [[ 1.  2. 60.]
 [ 1.  2. 50.]
 [ 0.  9. 50.]
 ...
 [ 0.  2. 65.]
 [ 1. 13. 85.]
 [ 1.  0. 60.]]


In [15]:
svc_lin.score(X_test, y_test)

0.8471867007672634

In [16]:
from sklearn.metrics import accuracy_score
y_pred = svc_lin.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8471867007672634


In [17]:
svc_lin.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [18]:
# Train the SVM model
svc_poly = SVC(kernel='poly')
svc_poly.fit(X_train, y_train)

# Get the support vectors
support_vectors = svc_poly.support_vectors_

# Explore the support vectors
print("Number of support vectors:", len(support_vectors))
print("Support Vectors:\n", support_vectors)

Number of support vectors: 1827
Support Vectors:
 [[ 1.  2. 60.]
 [ 1.  2. 50.]
 [ 0.  9. 50.]
 ...
 [ 0.  2. 65.]
 [ 1. 13. 85.]
 [ 1.  0. 60.]]


In [28]:
y_pred1 = svc_poly.predict(X_test)
accuracy = accuracy_score(y_test, y_pred1)
print("Accuracy:", accuracy)

Accuracy: 0.8471867007672634


In [20]:
# Train the SVM model
svc_rbf = SVC(kernel='rbf')
svc_rbf.fit(X_train, y_train)

# Get the support vectors
support_vectors = svc_rbf.support_vectors_

# Explore the support vectors
print("Number of support vectors:", len(support_vectors))
print("Support Vectors:\n", support_vectors)

Number of support vectors: 1889
Support Vectors:
 [[ 1.  2. 60.]
 [ 1.  2. 50.]
 [ 0.  9. 50.]
 ...
 [ 0.  9. 60.]
 [ 1.  3. 30.]
 [ 1. 13. 85.]]


In [32]:
y_pred2 = svc_rbf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred2)
print("Accuracy:", accuracy)

Accuracy: 0.8471867007672634


In [22]:
# Train the SVM model
svc_sig = SVC(kernel='sigmoid')
svc_sig.fit(X_train, y_train)

# Get the support vectors
support_vectors = svc_sig.support_vectors_

# Explore the support vectors
print("Number of support vectors:", len(support_vectors))
print("Support Vectors:\n", support_vectors)

Number of support vectors: 1634
Support Vectors:
 [[ 1.  2. 60.]
 [ 1.  2. 50.]
 [ 0.  9. 50.]
 ...
 [ 0.  8. 30.]
 [ 0.  6. 35.]
 [ 1.  3. 30.]]


In [31]:
y_pred3 = svc_sig.predict(X_test)
accuracy = accuracy_score(y_test, y_pred3)
print("Accuracy:", accuracy)

Accuracy: 0.739769820971867
